[package]

	name    = "ekke_filebrowser"
	version = "0.1.0"
	authors = [ "Naja Melan <najamelan@autistici.org>" ]
	edition = "2018"

[dependencies]

	"ekke_core" = { path = "../../ekke_core" }
	"ekke_io"   = { path = "../../ekke_io"   }
